### PR TITLE
Some more refactoring

### PR DESCRIPTION
**Pull request by akorb**
No big changes. Made some code neater. :)
About the "Improved formatting" commit. Do you use the default format rules of ReSharper and Visual Studio?

### CODE REVIEW

**Comment by CodeDead** [comment]
Yes, default rules but certain Resharper suggestions such as LINQ and certain comments in the code itself to 'shut resharper up' sometimes ;). Be careful when using Resharper in the NativeMethods class because it can render the program completely useless.

**Comment by akorb** [comment]
Ah I see. Don't worry, I don't even have ReSharper installed, but I know it :)

**Comment by CodeDead** [comment]
It can be very helpful to find issues and for formatting, do you use an alternative or just the default Visual Studio editor?

**Comment by akorb** [comment]
For sure, I love Resharper, I use it at work :)
I use the default VS editor. You can auto-format code whenever you want with the shortcut `Strg + K; D`

**Comment by CodeDead** [comment]
Ah yes, one of my favorite shortcuts that I just always seem to forget whenever I'm done with a coding session. I always tell myself: I'll do it later, when it's finished. The problem is that it's never really finished ;).

Anyway, thank you for all the help and improvements that you've made. Would you mind if I added a special section in the help documentation just for you (and anyone else who helps with the development of DeadLock) ?
It would basically be a thank-you note and a link to your profile (and whoever else contributes to the coding part of DeadLock) ;).

**Comment by akorb** [comment]
Sure, it would be a pleasure to see this :)

One more question. I just noticed, the user has to select a path for the updater executable. That's pretty uncommon. Any reason why not using the `%temp%` path for this?

**Comment by CodeDead** [comment]
Added a default download directory to the latest commit ;).

**Pull request merged**
