### PR TITLE
Some refactoring

### PR DESCRIPTION
**Pull request by akorb**
I implemented the correct async pattern for the Update process.
It's pretty often misused in 'ListViewLocker' too but I wanted first see whether such changes are fine for you.

The "A new update is available, do you want to update?" dialog blocks the GUI thread now. I think that offers probably a better user experience. I kept the actual FrmUpdater unblocking, maybe you want it exactly that way.

I hope I could contribute something helpful to your project :)

### CODE REVIEW

**Comment by CodeDead** [comment]
Thank you, your request has been accepted and is perfectly fine ;).
Thank you for improving DeadLock !

**Comment by CodeDead** [comment]
Hello !

We have looked at your Pull request and have merged it with the master branch of DeadLock. Thank you for helping us improve DeadLock ;) !

Updates themselves should be done in the background (as you’ve implemented correctly) without locking up the GUI because this can significantly increase start-up times for DeadLock since the update function is called when the main form is loading. As it is right now with your pull request, everything is running fine. Whether the ‘Do you want to update’ dialog blocks the GUI is not actually a problem so we’ll keep it as you’ve implemented it ;).

Thank you for the help !

Kind regards

Alessandro Mercier
http://codedead.com/

 

Van: Andreas Korb [mailto:notifications@github.com] 
Verzonden: zaterdag 16 januari 2016 0:16
Aan: CodeDead/DeadLock <DeadLock@noreply.github.com>
Onderwerp: [DeadLock] Some refactoring (#1)

 

I implemented the correct async pattern for the Update process.
It's pretty often misused in 'ListViewLocker' too but I wanted first see whether such changes are fine for you.

The "A new update is available, do you want to update?" dialog blocks the GUI thread now. I think that offers probably a better user experience. I kept the actual FrmUpdater unblocking, maybe you want it exactly that way.

I hope I could contribute something helpful to your project :)

  _____  


You can view, comment on, or merge this pull request online at:


  https://github.com/CodeDead/DeadLock/pull/1


Commit Summary


*	Removed using
*	Improved async pattern
*	Removed redundant exception handler


File Changes


*	M DeadLock/Classes/ListViewLocker.cs <https://github.com/CodeDead/DeadLock/pull/1/files#diff-0>  (4) 
*	M DeadLock/Forms/FrmMain.cs <https://github.com/CodeDead/DeadLock/pull/1/files#diff-1>  (59) 
*	M DeadLock/Properties/AssemblyInfo.cs <https://github.com/CodeDead/DeadLock/pull/1/files#diff-2>  (1) 
*	M RegManager/Properties/AssemblyInfo.cs <https://github.com/CodeDead/DeadLock/pull/1/files#diff-3>  (1) 


Patch Links:


*	https://github.com/CodeDead/DeadLock/pull/1.patch
*	https://github.com/CodeDead/DeadLock/pull/1.diff

**Comment by akorb** [comment]
I'm glad you like it :)
Did you actually intend to revert the 'async' changes with your latest commit? I'm a little bit confused now.

**Comment by CodeDead** [comment]
Hello sir,



No, an issue occurred when the project was synced on my machine. I’m using the GitHub for Visual Studio extension but apparently it contains a couple of bugs. Will be fixed shortly ;) !

Kind regards

Alessandro Mercier
http://codedead.com/

 

Van: Andreas Korb [mailto:notifications@github.com] 
Verzonden: maandag 18 januari 2016 18:31
Aan: CodeDead/DeadLock <DeadLock@noreply.github.com>
CC: CodeDead <admin@codedead.com>
Onderwerp: Re: [DeadLock] Some refactoring (#1)

 

I'm glad you like it :)
Did you actually intend to revert the 'async' changes with your latest commit? I'm a little bit confused now.

**Comment by CodeDead** [comment]
The issue has been fixed ;).

**Pull request merged**
